In [4]:
import numpy as np


array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
arr=np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr.shape=(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4),order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [16]:
arr = np.arange(8)
arr.shape = (2, 4)
arr
arr_trans=arr.transpose()
arr_trans



array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [19]:
arr=np.linspace(1,2,6)
arr


array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [20]:
print(arr[2])

1.4


In [21]:
print(arr[2:4])


[1.4 1.6]


In [22]:
print(arr[::-1])


[2.  1.8 1.6 1.4 1.2 1. ]


In [25]:
nd_array=np.linspace(0,6,12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [29]:
nd_array[1,2]


3.0

In [28]:
nd_array[:2,2]

array([1., 3.])

In [30]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [31]:
nd_array[:,2:4]


array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [32]:
nd_array[:2]


array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [34]:
data=np.array([4,9,-4,3])
roots=np.sqrt(data)
roots

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4596\675264307.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots=np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [35]:
np.isnan(roots)

array([False, False,  True, False])

In [37]:
roots[np.isnan(roots)]


array([nan])

In [38]:
roots[np.isnan(roots)]=0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [39]:
sum(roots)

6.732050807568877

In [2]:
import numpy as np
simplelist = [19, 242, 14, 152, 142, 1000]
lst_avr=np.average(simplelist)
print(lst_avr)

261.5


In [3]:
import pandas as pd
pd.__version__

'1.4.3'

In [ ]:
print(pd.__name__)