In [3]:
import numpy as np
np.random.rand()

0.9946900818815125

In [4]:
np.random.rand()*100

96.63239339244068

In [5]:
np.random.rand(5)

array([0.69834089, 0.03753167, 0.7359925 , 0.97744197, 0.66497096])

In [6]:
np.random.rand(2,3)

array([[0.87231808, 0.15696731, 0.46762845],
       [0.45706576, 0.59516821, 0.83957485]])

In [7]:
shape=(2,3)
np.random.sample(shape)


array([[0.07761879, 0.5496598 , 0.96184353],
       [0.0471352 , 0.18203173, 0.61211794]])

In [10]:
np.random.uniform()


0.10197016578872642

In [50]:
np.random.uniform(-30,50)

16.582154293804777

In [15]:
np.random.uniform(0.5,0.75,size=5)

array([0.57765989, 0.62758898, 0.56424382, 0.74415449, 0.68377444])

In [16]:
np.random.uniform(-1000,500,size=(2,3))


array([[ -95.63969231,  307.07145172, -495.28186275],
       [-631.04217961, -167.60941841, -702.2012085 ]])

In [17]:
np.random.randint(4,size=(2,3))

array([[0, 2, 0],
       [0, 2, 1]])

In [19]:
np.random.randint(6,12,size=(3,3))

array([[10, 11,  9],
       [11,  8,  6],
       [10,  7,  9]])

In [52]:
arr=np.arange(6)
arr
print(np.random.shuffle(arr))
arr

None


array([0, 2, 3, 1, 5, 4])

In [30]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled=np.random.permutation(playlist)
playlist
shuffled

array(['Pink Floyd', 'The Beatles', 'ACDC', 'Deep Purple'], dtype='<U11')

In [32]:
np.random.permutation(10)

array([7, 3, 0, 1, 4, 2, 8, 9, 5, 6])

In [36]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice=np.random.choice(workers,size=2,replace=False)
print(choice)

['Maria' 'Nikita']


In [38]:
choice=np.random.choice([1,2,3,4,5,6],size=10)
print(choice)


[2 3 4 6 4 6 6 4 2 2]


In [40]:
np.random.seed(23)
np.random.randint(10,size=(3,4))


array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [46]:
np.random.seed(100)
print(np.random.randint(10,size=3))
print(np.random.randint(10,size=3))

[8 8 3]
[7 7 0]
