In [2]:
from collections import Counter
c=Counter



In [23]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']
counter_moscow=Counter(cars_moscow)
counter_spb=Counter(cars_spb)
print(counter_moscow)
print(counter_spb)
counter_moscow.subtract(counter_spb)
print(counter_moscow)

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [24]:
counter_moscow=Counter(cars_moscow)
counter_spb=Counter(cars_spb)
print(counter_moscow-counter_spb)


Counter({'black': 2, 'yellow': 1})


In [32]:
print(counter_moscow.most_common())

[('black', 4), ('yellow', 3), ('white', 2)]


In [36]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]
from collections import defaultdict
groups=defaultdict(list)
for student, group in students:
    groups[group].append(student)
print(groups[3])

['Petrov', 'Markov']


In [5]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages=OrderedDict(data)
print(ordered_client_ages)

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [45]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)
ordered_client_ages['Nikita']=18
print(ordered_client_ages)
del ordered_client_ages['Andrey']
print(ordered_client_ages)
ordered_client_ages['Andrey']=23
print(ordered_client_ages)



temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5),
        ('2004', -8.2), ('2005', -1.6), ('2006', -5.9), ('2007', -2.4),
        ('2008', -1.7), ('2009', -3.5), ('2010', -12.1), ('2011', -5.8),
        ('2012', -4.9), ('2013', -6.1), ('2014', -6.9), ('2015', -2.7),
        ('2016', -11.2), ('2017', -3.9), ('2018', -2.9), ('2019', -6.5),
        ('2020', 1.5)]
from collections import OrderedDict
temps.sort(key=lambda x: x[1], reverse=True)
od = OrderedDict(temps)
print(od)

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18), ('Andrey', 23)])
OrderedDict([('2020', 1.5), ('2005', -1.6), ('2008', -1.7), ('2007', -2.4), ('2001', -2.5), ('2015', -2.7), ('2018', -2.9), ('2009', -3.5), ('2017', -3.9), ('2000', -4.4), ('2002', -4.4), ('2012', -4.9), ('2011', -5.8), ('2006', -5.9), ('2013', -6.1), ('2019', -6.5), ('2014', -6.9), ('2004', -8.2), ('2003', -9.5), ('2016', -11.2), ('2010', -12.1)])


In [18]:
from collections import deque
dq=deque()
print(dq)


deque([])


In [22]:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
print(clients[2])
first_client=clients.popleft()
second_client=clients.popleft()
print('First client:',first_client)
print('Second client:',second_client)
print(clients)


deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
Smirnov
First client: Ivanov
Second client: Petrov
deque(['Smirnov', 'Tikhonova'])


In [23]:
clients.appendleft('Vip client')
print(clients)


deque(['Vip client', 'Smirnov', 'Tikhonova'])


In [24]:
tired_client=clients.pop()
print(clients)


deque(['Vip client', 'Smirnov'])


In [25]:
clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
del clients[2]
print(clients)


deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
deque(['Ivanov', 'Petrov', 'Tikhonova'])


In [26]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)


deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [27]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)


deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])


In [28]:
limited = deque(maxlen=3)
print(limited)


deque([], maxlen=3)


In [29]:
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)


deque([5, 6, 7], maxlen=3)


In [30]:
limited.extend([1,2,3])
print(limited)

deque([1, 2, 3], maxlen=3)


In [31]:
print(limited.append(8))
print(limited)


None
deque([2, 3, 8], maxlen=3)


In [32]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]
days=deque(maxlen=7)
for temp in temps:
    days.append(temp)
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
print('')

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 


In [33]:
dq = deque([1,2,3,4,5])
print(dq)


deque([1, 2, 3, 4, 5])


In [34]:
dq.reverse()
print(dq)


deque([5, 4, 3, 2, 1])


In [36]:
dq = deque([1,2,3,4,5])
print(dq)
dq.rotate(2)
print(dq)


deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [38]:
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
print(dq.count(4))


2
6


In [39]:
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
dq.clear()
print(dq)


[]


In [47]:
from hidden import users
from collections import deque
users = deque(users)
user_id = users.popleft()
print(user_id)

ModuleNotFoundError: No module named 'hidden'

In [8]:
from collections import Counter
north_list = [elem for bill in north for elem in bill]
south_list = [elem for bill in south for elem in bill]
center_list = [elem for bill in center for elem in bill]
 
c = Counter(center_list)
s = Counter(south_list)
n = Counter(north_list)
 
print(n.most_common()[-1])

NameError: name 'north' is not defined

In [2]:
import numpy as np

In [4]:
n_min=-(2**16)/2
print(n_min)
n_max=(2**16)/2-1
print(n_max)

-32768.0
32767.0


In [5]:
a=np.int8(127)
print(a)
print(type(a))
np.iinfo(np.int64)



127
<class 'numpy.int8'>


iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [6]:
b=np.uint8(-456)
print(type(b))
np.iinfo(b)
print(b)

<class 'numpy.uint8'>
56


In [21]:
a=np.int32(1000)
b=a+25
print(b)
print(type(b))



1025
<class 'numpy.int32'>


In [24]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(np.int64(a)+np.int64(b))

4294967215


In [4]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [11]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
arr.dtype

dtype('int32')

In [12]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
nd_arr.dtype

dtype('int32')

In [18]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
arr[2]=2000
arr


array([  1,   5, -48,   9,  10], dtype=int8)

In [19]:
arr[2] = 125.5
arr


array([  1,   5, 125,   9,  10], dtype=int8)

In [25]:
arr[2] = '29'
arr

array([ 1,  5, 29,  9, 10], dtype=int8)

In [27]:
arr = np.float64(arr)
arr

array([ 1.,  5., 29.,  9., 10.])

In [38]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float64)
arr

array([ 3.4523400e+05,  8.7636212e+05,  0.0000000e+00, -1.0000000e+03,
        9.9999999e+07])

In [44]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
nd_arr.itemsize

2

In [45]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [48]:
zeros_1d = np.zeros((5,4,3,),dtype=np.float32)
zeros_1d
print(zeros_1d.shape)

(5, 4, 3)


In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [52]:
np.arange(2.5,5,0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [54]:
arr = np.linspace(1, 2, 10,endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [55]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)

0.1111111111111111


In [60]:
arr, step = np.linspace(-6, 21, 60, endpoint=False,retstep=True)
print(step)


0.45
