In [1]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1*vec2

array([24. , 24. , 25.2, 32.5])

In [4]:
vec=np.arange(5)
vec*10


array([ 0, 10, 20, 30, 40])

In [5]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1>vec2

array([False, False,  True, False])

In [6]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [8]:
vec=np.array([3,4])
length=np.sqrt(np.sum(vec**2))
print(length)

5.0


In [9]:
length=np.linalg.norm(vec)
print(length)

5.0


In [10]:
vec1=np.array([0,3,5])
vec2=np.array([12,4,7])
distance=np.sqrt(np.sum((vec1-vec2)**2))
distance

12.206555615733702

In [11]:
vec1=np.array([0,3,5])
vec2=np.array([12,4,7])
distance=np.linalg.norm(vec1-vec2)
distance

12.206555615733702

In [13]:
vec1=np.arange(1,6)
vec2=np.linspace(10,20,5)
scalar_product=np.sum(vec1*vec2)
scalar_product

250.0

In [14]:
scalar_product=np.dot(vec1,vec2)
scalar_product

250.0

In [15]:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)

0

In [20]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

distance1=np.linalg.norm(a-b)
distance1


85.901105930017

In [21]:
distance2=np.linalg.norm(a-c)
distance2

49.13247398615299

In [22]:
distance3=np.linalg.norm(b-c)
distance3

120.6358155772986

In [27]:
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
scalar_product1=np.dot(a,b)
scalar_product1

34

In [28]:
scalar_product2=np.dot(a,c)
scalar_product2

4828

In [29]:
scalar_product3=np.dot(b,c)
scalar_product3

68

In [30]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()

1

In [31]:
np.max(vec)

28

In [32]:
vec.mean()

10.75

In [33]:
vec.max()

28